-- Create a table to store the target date
CREATE TABLE target_date (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT UNIQUE NOT NULL,
  t_date TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Insert the target date
INSERT INTO target_date (event_name, t_date)
VALUES ('countdown_end', '2026-11-16 00:00:00+00');

-- Create a function to get the current server time
CREATE OR REPLACE FUNCTION get_server_time()
RETURNS TIMESTAMP WITH TIME ZONE AS $$
BEGIN
  RETURN NOW();
END;
$$ LANGUAGE plpgsql;

-- Create a table for the GTA VI poll
CREATE TABLE gta_vi_poll (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote TEXT NOT NULL CHECK (vote IN ('yes', 'no')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
